// KeyMarks.tsx — the drawn Διαγραφή (backspace) and Καταχώρηση (submit) marks.
//
// Graduated out of `src/components/leksokipos/icons.tsx` when Leksiarxeio and Vres
// Tin Frasi replaced their `⌫` / `↵` glyph keys with the same two drawings — three
// genuine consumers, which is the bar for shared/ (CLAUDE.md standing rule). The
// two marks nobody else draws (Καθαρισμός, Ανακάτεμα) stayed behind in Leksokipos.
//
// Every mark is authored on a 24×24 canvas with round caps and joins, no fill, and
// stroke="currentColor" — the colour is decided by the BUTTON, which is what lets
// one drawing serve a filled action key, a neutral one, and a muted disabled one.
// Path data is generated by .claude/aiHelper/html/leksokipos-icons.gen.js; copy
// from there rather than redrawing by eye.

/** Default rendered size of a mark, in px (spec: 22 on a 24×24 canvas). */
export const ICON_PX = 22;

/** Line weight shared by the outline marks; the check is heavier (2.4). */
const STROKE = 2.2;

export interface MarkProps {
  /** Extra classes for the <svg> — layout only, never colour. */
  className?: string;
  /** Rendered px; the canvas is always 24×24, so this only scales the drawing. */
  size?: number;
}

export function Mark({ className = "", size = ICON_PX, children }: MarkProps & { children: React.ReactNode }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={size}
      height={size}
      fill="none"
      stroke="currentColor"
      strokeWidth={STROKE}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
      className={`block ${className}`}
    >
      {children}
    </svg>
  );
}

/** Διαγραφή — a backspace key outline with a left arrow inside it. */
export function DeleteMark({ className, size }: MarkProps = {}) {
  return (
    <Mark className={className} size={size}>
      <path d="M9.6 4.9H19.4A2.2 2.2 0 0 1 21.6 7.1V16.9A2.2 2.2 0 0 1 19.4 19.1H9.6L2.9 12Z" />
      <path d="M18.4 12H12.6M15 9.6L12.6 12L15 14.4" />
    </Mark>
  );
}

/** Καταχώρηση — a check. Drawn a touch heavier than the outline marks (2.4). */
export function SubmitMark({ className, size }: MarkProps = {}) {
  return (
    <Mark className={className} size={size}>
      <path d="M4.6 12.6L9.8 17.8L19.4 6.8" strokeWidth={2.4} />
    </Mark>
  );
}
