// icons.tsx — the four drawn marks on the Leksokipos action buttons.
//
// Two of the four now live in `src/components/shared/KeyMarks.tsx`: Leksiarxeio and
// Vres Tin Frasi draw the same backspace and check on their keyboards, which is the
// three-consumer bar for shared/ (CLAUDE.md). They are re-exported here so the
// Leksokipos action row keeps importing all four marks from one place.
//
// Καθαρισμός and Ανακάτεμα stayed game-scoped: no second game draws them, and
// nothing graduates speculatively.
//
// Every mark is authored on a 24×24 canvas with round caps and joins, no fill, and
// stroke="currentColor" — the colour is decided by the BUTTON, which is what lets
// one drawing serve the green enabled state and the muted disabled one. Path data
// is generated by .claude/aiHelper/html/leksokipos-icons.gen.js; copy from there
// rather than redrawing by eye.

import { Mark, type MarkProps } from "@/components/shared/KeyMarks";

export { DeleteMark, SubmitMark } from "@/components/shared/KeyMarks";

/** The action row draws its marks 15% larger, in step with its larger box. */
export const ICON_PX_ROW = 25;

/** Καθαρισμός — a circle with an Χ inside it. */
export function ClearMark({ className, size }: MarkProps = {}) {
  return (
    <Mark className={className} size={size}>
      <path d="M3.2 12a8.8 8.8 0 1 0 17.6 0a8.8 8.8 0 1 0 -17.6 0Z" />
      <path d="M8.8 8.8L15.2 15.2M15.2 8.8L8.8 15.2" />
    </Mark>
  );
}

/** Ανακάτεμα — two separate half-arcs facing opposite ways, each arrow-headed. */
export function ShuffleMark({ className, size }: MarkProps = {}) {
  return (
    <Mark className={className} size={size}>
      <path d="M5.07 8A8 8 0 0 1 18.93 8M15.34 6.37L18.93 8L19.33 4.08" />
      <path d="M18.93 16A8 8 0 0 1 5.07 16M8.66 17.63L5.07 16L4.67 19.92" />
    </Mark>
  );
}
