// icons.tsx — the four drawn marks on the Leksokipos action buttons.
//
// Game-scoped on purpose: nothing graduates to src/components/shared/ until a
// second game genuinely needs it, and today none does (CLAUDE.md standing rule).
//
// Every mark is authored on a 24×24 canvas with round caps and joins, no fill,
// and stroke="currentColor" — the colour is decided by the BUTTON, which is what
// lets one drawing serve the green enabled state and the muted disabled one.
// Path data is generated by .claude/aiHelper/html/leksokipos-icons.gen.js; copy
// from there rather than redrawing by eye.

/** Rendered size of every mark, in px (spec: 22 on a 24×24 canvas). */
const ICON_PX = 22;

/** Line weight shared by three of the four marks; the check is heavier (2.4). */
const STROKE = 2.2;

interface MarkProps {
  /** Extra classes for the <svg> — layout only, never colour. */
  className?: string;
}

function Mark({ className = "", children }: MarkProps & { children: React.ReactNode }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width={ICON_PX}
      height={ICON_PX}
      fill="none"
      stroke="currentColor"
      strokeWidth={STROKE}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
      className={`block ${className}`}
    >
      {children}
    </svg>
  );
}

/** Διαγραφή — a backspace key outline with a left arrow inside it. */
export function DeleteMark({ className }: MarkProps = {}) {
  return (
    <Mark className={className}>
      <path d="M9.6 4.9H19.4A2.2 2.2 0 0 1 21.6 7.1V16.9A2.2 2.2 0 0 1 19.4 19.1H9.6L2.9 12Z" />
      <path d="M18.4 12H12.6M15 9.6L12.6 12L15 14.4" />
    </Mark>
  );
}

/** Καθαρισμός — a circle with an Χ inside it. */
export function ClearMark({ className }: MarkProps = {}) {
  return (
    <Mark className={className}>
      <path d="M3.2 12a8.8 8.8 0 1 0 17.6 0a8.8 8.8 0 1 0 -17.6 0Z" />
      <path d="M8.8 8.8L15.2 15.2M15.2 8.8L8.8 15.2" />
    </Mark>
  );
}

/** Ανακάτεμα — two separate half-arcs facing opposite ways, each arrow-headed. */
export function ShuffleMark({ className }: MarkProps = {}) {
  return (
    <Mark className={className}>
      <path d="M5.07 8A8 8 0 0 1 18.93 8M15.34 6.37L18.93 8L19.33 4.08" />
      <path d="M18.93 16A8 8 0 0 1 5.07 16M8.66 17.63L5.07 16L4.67 19.92" />
    </Mark>
  );
}

/** Καταχώρηση — a check. Drawn a touch heavier than the other three (2.4). */
export function SubmitMark({ className }: MarkProps = {}) {
  return (
    <Mark className={className}>
      <path d="M4.6 12.6L9.8 17.8L19.4 6.8" strokeWidth={2.4} />
    </Mark>
  );
}
