// deploymentReadiness.test.ts
// Catches the class of bug where a file is statically imported by a data loader
// but is listed in .gitignore — meaning it exists locally but Vercel won't have it.
//
// How it works:
//   1. Parse .gitignore into minimatch patterns (simple line-by-line, no fancy glob lib needed)
//   2. Assert that every data file that the app statically imports at build time
//      is NOT matched by any .gitignore pattern
//   3. Assert that the files physically exist on disk (catches "file deleted but import left")

import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "fs";

import { resolve } from "path";

const ROOT = resolve(__dirname, "../../../");

// ── Parse .gitignore ──────────────────────────────────────────────────────────

function loadGitignorePatterns(): string[] {
  const raw = readFileSync(resolve(ROOT, ".gitignore"), "utf8");
  return raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

/**
 * Minimal gitignore matcher — handles:
 *   - Exact paths:           src/data/words-en.json
 *   - Glob suffix:           src/data/leksiarxeio/words-*.json
 *   - Leading slash (root):  /node_modules
 */
function isIgnored(filePath: string, patterns: string[]): boolean {
  // Normalise to forward slashes, strip leading ./
  const norm = filePath.replace(/\\/g, "/").replace(/^\.\//, "");

  for (const pattern of patterns) {
    const p = pattern.replace(/^\//, ""); // strip leading /

    if (p.includes("*")) {
      // Convert glob to regex: escape dots, replace * with [^/]*
      const regexStr = p
        .replace(/\./g, "\\.")
        .replace(/\*/g, "[^/]*");
      const re = new RegExp(`(^|/)${regexStr}($|/)`);
      if (re.test(norm)) return true;
    } else {
      // Exact match or path-prefix match
      if (norm === p || norm.startsWith(p + "/") || norm.endsWith("/" + p)) {
        return true;
      }
    }
  }
  return false;
}

// ── Files the app statically imports at build time ────────────────────────────
// This list must be kept in sync with actual `import ... from` statements in
// src/data/**/index.ts. Add an entry here whenever you add a new static import.

const STATICALLY_IMPORTED_DATA_FILES = [
  // Leksiarxeio — one list per length (answers + valid guesses, same file)
  // words-2 and words-3 are also used by VresTinFrasi for short-word validation
  "src/data/leksiarxeio/words-2.json",
  "src/data/leksiarxeio/words-3.json",
  "src/data/leksiarxeio/words-4.json",
  "src/data/leksiarxeio/words-5.json",
  "src/data/leksiarxeio/words-6.json",
  "src/data/leksiarxeio/words-7.json",
  "src/data/leksiarxeio/words-8.json",
  // Leksiarxeio curated answer pools — also statically imported by the
  // Leksodromia data loader (read-only reuse, direct JSON imports)
  "src/data/leksiarxeio/answers-4.json",
  "src/data/leksiarxeio/answers-5.json",
  "src/data/leksiarxeio/answers-6.json",
  "src/data/leksiarxeio/answers-7.json",
  "src/data/leksiarxeio/answers-8.json",
  // Leksindeseis
  "src/data/leksindeseis/puzzles-connections.json",
  // Leksokipos — pre-built puzzles
  "src/data/leksokipos/puzzles-el.json",
  // Full word list — statically imported by /api/validate-words; buildCustomPuzzle
  // loads it via dynamic import() only (see Fluid CPU guard below), but the file
  // must still exist and be committed for the bundler to split it into a chunk
  "src/data/words-el.json",
  // Leksokipos — slim index (letters/dates only) used by the /leksokipos
  // redirect page; generated by `npm run generate-puzzle-index`
  "src/data/leksokipos/puzzles-index-el.json",
];

// ── Tests ─────────────────────────────────────────────────────────────────────

// ── Fluid CPU guard — words-el.json must stay a lazy load ─────────────────────
// The 19.5 MB word list is only needed by buildCustomPuzzle's cache-miss path
// (arbitrary /leksokipos/[center]/[outer] combos). A static import would make
// EVERY route that touches the puzzle data layer parse it on cold start
// (~0.5–1 s of billed Fluid Active CPU per cold invocation). Daily-puzzle
// renders must parse only puzzles-el.json.

describe("Fluid CPU guard — leksokipos data loader lazy-loads words-el.json", () => {
  const loaderSource = readFileSync(
    resolve(ROOT, "src/data/leksokipos/index.ts"),
    "utf8",
  );

  it("does not statically import words-el.json", () => {
    // Matches top-level `import x from "...words-el.json"` (any quote style/path)
    const staticImport = /import\s+[\w{},*\s]+from\s+["'][^"']*words-el\.json["']/;
    expect(
      staticImport.test(loaderSource),
      "src/data/leksokipos/index.ts statically imports words-el.json — " +
        "this makes every consumer of the puzzle data layer parse 19.5 MB on " +
        "cold start. Use `await import(...)` inside buildCustomPuzzle instead.",
    ).toBe(false);
  });

  it("still references the word list via dynamic import()", () => {
    // Guards against the opposite failure: deleting the word-list usage
    // entirely (custom puzzles would silently have zero valid words).
    const dynamicImport = /import\(\s*["'][^"']*words-el\.json["']\s*\)/;
    expect(
      dynamicImport.test(loaderSource),
      "Expected buildCustomPuzzle to load words-el.json via dynamic import().",
    ).toBe(true);
  });
});

// ── Fluid CPU guard — prebuilt combos must stay prerendered ───────────────────
// generateStaticParams on the [center]/[outer] page prerenders every prebuilt
// puzzle combo at build time, so daily-puzzle traffic is served by the CDN with
// zero Fluid CPU. Removing it would put every daily player back on a Fluid
// function (~1.4 s CPU per cold render — the dominant burner before this fix).

describe("Fluid CPU guard — [center]/[outer] page prerenders prebuilt combos", () => {
  const pageSource = readFileSync(
    resolve(ROOT, "src/app/leksokipos/[center]/[outer]/page.tsx"),
    "utf8",
  );

  it("exports generateStaticParams delegating to getPrebuiltPuzzleParams", () => {
    expect(
      /export\s+(async\s+)?function\s+generateStaticParams/.test(pageSource),
      "The [center]/[outer] page must export generateStaticParams — " +
        "without it, every daily combo renders on a Fluid function.",
    ).toBe(true);
    expect(
      pageSource.includes("getPrebuiltPuzzleParams("),
      "generateStaticParams must source its params from getPrebuiltPuzzleParams " +
        "(slim index) — see puzzleIndex.test.ts for the canonical-param contract.",
    ).toBe(true);
  });

  it("sources the params from the slim puzzleIndex module, not the full loader", () => {
    expect(
      pageSource.includes("@/data/leksokipos/puzzleIndex"),
      "getPrebuiltPuzzleParams must be imported from @/data/leksokipos/puzzleIndex " +
        "(108 KB index) — importing it via the full loader would work but couples " +
        "the param source to the 4 MB puzzles-el.json module graph.",
    ).toBe(true);
  });
});

describe("Deployment readiness — statically imported data files", () => {
  const patterns = loadGitignorePatterns();

  for (const file of STATICALLY_IMPORTED_DATA_FILES) {
    it(`${file} — exists on disk`, () => {
      expect(
        existsSync(resolve(ROOT, file)),
        `File not found: ${file}\nVercel will fail to build without it.`,
      ).toBe(true);
    });

    it(`${file} — not gitignored (Vercel can see it)`, () => {
      expect(
        isIgnored(file, patterns),
        `${file} is matched by .gitignore.\nVercel clones the repo and will NOT have this file at build time.\nEither commit it (remove from .gitignore) or change the import to be dynamic.`,
      ).toBe(false);
    });
  }
});
