// Λογοπαίγνιο — the seed candidate list (handoff logopaignio-content-pool.md).
//
// One row per candidate brand. This file is DATA ONLY: no fetching, no cropping.
// The fetcher (scripts/fetch-logopaignio-logos.mjs) resolves each row's asset via
// the Wikimedia Commons API, and the preview generator renders them for the human
// eye check. Nothing here ships to the app — a brand only becomes a puzzle after
// the operator approves it and it is written into src/data/logopaignio/puzzles-el.json.
//
// FIELDS
//   id        stable slug — also the raw filename stem and the future puzzle id
//   brand     canonical display name (what the player must guess)
//   sector    Greek sector label, shown in-game as the permanent free hint
//   accept    draft accept-list — Greek form + Latin form + common variants.
//             MUST bridge the Greek⇄Latin fork; the operator extends it on approval.
//   search    Commons search terms, tried in order until a file is found.
//             null = no expected public asset (manual sourcing case).
//   note      guidance for the eye check (why it might fail the icon-only filter)
//
// RULES (see the handoff):
//   • current logo only  • defunct/nostalgia marks allowed  • pure wordmarks are
//   REJECTED (the icon-only filter) — they are unguessable once name-stripped.
//
// SCOPE CHANGE (operator decision, 2026-07-27): the "founded/HQ'd in Greece" half
// of the Greek-origin rule is DROPPED. The pool is now "brands a Greek audience
// recognizes", regardless of origin — so DHL, Revolut, Sprite, Fanta, Pepsi,
// Wolt, Groupama et al. are in scope. Recognizability to a Greek audience is
// still required; this widens the pool toward the 150 launch floor without
// touching the icon-only filter, which is what actually keeps the game playable.
//
// SUB-BRANDS ALLOWED (operator decision, 2026-07-27 — expansion #2). The former
// "master/parent brand only" rule is RELAXED, not merely excepted: the household
// name is often the product, not the company. Mythos and ΑΛΦΑ (Αθηναϊκή
// Ζυθοποιία), Lacta (Mondelez), Molto and 7Days (Chipita), Πάμε Στοίχημα and
// ΤΖΟΚΕΡ (ΟΠΑΠ), Nescafé (Nestlé) are all in scope alongside their parents. The
// Cosmote caveat still applies in spirit: if the only separable mark is a foreign
// parent's and carries none of the brand's own identity, drop it.
//
// SECTOR MERGES (expansion #2). Sector is the in-game free hint, so fewer, fatter
// categories give less away than many thin ones:
//   • «Αναψυκτικά» + waters + beer + wine/spirits → one «Υγρά» bucket. The name is
//     a WORKING LABEL, not final — the operator will rename it before launch.
//   • «Καφέ» (chains) folded into «Εστίαση», which is no longer deferred.
//   • «Ηλεκτρονικά» folded into «Λιανική» — two rows was too thin to be a hint.
//   • «Τυριά & αλλαντικά» added as a new sector; it has no sensible parent.
//
// SECTORS REMOVED (expansion #2): «Αεροπορική εταιρεία», «Κατασκευές»,
// «Ενέργεια», «Τηλεπικοινωνίες», «Φαρμακευτικά», and most of «Βιομηχανία»
// (kept: Πίτσος, ΤΙΤΑΝ, Alumil, Ηρακλής). Olympic Airways was RESCUED from the
// deleted airline sector into «Μεταφορές» — the six meander rings are the
// strongest single mark in the pool and deleting the sector should not cost it.

/**
 * @typedef {Object} SeedBrand
 * @property {string} id
 * @property {string} brand
 * @property {string} sector
 * @property {string[]} accept
 * @property {string[]|null} search
 * @property {string} [note]
 */

/** @type {SeedBrand[]} */
export const SEED_BRANDS = [
  // ─── Τράπεζα ─────────────────────────────────────────────────────────────
  {
    id: "alpha-bank",
    brand: "Alpha Bank",
    sector: "Τράπεζα",
    accept: ["Alpha Bank", "Άλφα Μπανκ", "Alpha", "Άλφα", "Αλφα Μπανκ"],
    search: ["Alpha Bank logo"],
    note: "PoC ✅ keep — navy square + white A is a clean standalone mark.",
  },
  {
    id: "ethniki-trapeza",
    brand: "Εθνική Τράπεζα",
    sector: "Τράπεζα",
    accept: ["Εθνική Τράπεζα", "Εθνικη Τραπεζα", "Εθνική", "ΕΤΕ", "National Bank of Greece", "NBG"],
    search: ["National Bank of Greece logo", "Εθνική Τράπεζα logo"],
    note: "Fire-horse/flame emblem — check it separates from the wordmark.",
  },
  {
    id: "peiraios",
    brand: "Τράπεζα Πειραιώς",
    sector: "Τράπεζα",
    accept: ["Τράπεζα Πειραιώς", "Τραπεζα Πειραιως", "Πειραιώς", "Πειραιως", "Piraeus Bank", "Piraeus"],
    search: ["Piraeus Bank logo", "Piraeus Financial Holdings logo"],
  },
  {
    id: "eurobank",
    brand: "Eurobank",
    sector: "Τράπεζα",
    accept: ["Eurobank", "Γιούρομπανκ", "Ευρωμπανκ", "Γιουρομπανκ"],
    search: ["Eurobank logo", "Eurobank Ergasias logo"],
  },
  {
    id: "optima-bank",
    brand: "Optima Bank",
    sector: "Τράπεζα",
    accept: ["Optima Bank", "Optima", "Όπτιμα", "Οπτιμα"],
    search: ["Optima Bank logo"],
  },
  {
    id: "attica-bank",
    brand: "Attica Bank",
    sector: "Τράπεζα",
    accept: ["Attica Bank", "Αττικής", "Τράπεζα Αττικής", "Attica"],
    search: ["Attica Bank logo"],
  },
  {
    id: "revolut",
    brand: "Revolut",
    sector: "Τράπεζα",
    accept: ["Revolut", "Ρεβολούτ", "Ρεβολουτ"],
    search: ["Revolut logo"],
  },

  // ─── Εταιρείες ───────────────────────────────────────────────────────────
  {
    id: "interamerican",
    brand: "Interamerican",
    sector: "Εταιρείες",
    accept: ["Interamerican", "Ίντεραμέρικαν", "Ιντεραμερικαν"],
    search: ["Interamerican logo"],
  },
  {
    id: "ethniki-asfalistiki",
    brand: "Εθνική Ασφαλιστική",
    sector: "Εταιρείες",
    accept: ["Εθνική Ασφαλιστική", "Εθνικη Ασφαλιστικη", "Ethniki Asfalistiki"],
    search: ["Ethniki Asfalistiki logo", "Εθνική Ασφαλιστική logo"],
  },
  {
    id: "ergo",
    brand: "ERGO",
    sector: "Εταιρείες",
    accept: ["ERGO", "Έργκο", "Εργκο", "ERGO Ασφαλιστική"],
    search: ["ERGO insurance logo"],
  },
  {
    id: "minetta",
    brand: "Μινέττα",
    sector: "Εταιρείες",
    accept: ["Μινέττα", "Μινεττα", "Minetta", "Ασφάλειαι Μινέττα"],
    search: ["Minetta insurance logo"],
  },
  {
    id: "eurolife",
    brand: "Eurolife FFH",
    sector: "Εταιρείες",
    accept: ["Eurolife", "Eurolife FFH", "Γιουρολάιφ", "Ευρωλάιφ"],
    search: ["Eurolife FFH logo"],
  },
  {
    id: "ydrogios",
    brand: "Υδρόγειος",
    sector: "Εταιρείες",
    accept: ["Υδρόγειος", "Υδρογειος", "Ydrogios", "Υδρόγειος Ασφαλιστική"],
    search: ["Ydrogios insurance logo"],
  },
  {
    id: "interlife",
    brand: "Interlife",
    sector: "Εταιρείες",
    accept: ["Interlife", "Ίντερλαϊφ", "Ιντερλαιφ"],
    search: ["Interlife insurance logo"],
  },
  {
    id: "wakam",
    brand: "Wakam",
    sector: "Εταιρείες",
    accept: ["Wakam", "Γουακάμ", "Βακάμ"],
    search: ["Wakam logo"],
  },

  // ─── Σούπερ μάρκετ ───────────────────────────────────────────────────────
  {
    id: "ab-vassilopoulos",
    brand: "ΑΒ Βασιλόπουλος",
    sector: "Σούπερ μάρκετ",
    accept: ["ΑΒ Βασιλόπουλος", "ΑΒ Βασιλοπουλος", "Βασιλόπουλος", "Βασιλοπουλος", "ΑΒ", "AB Vassilopoulos", "AB"],
    search: ["Alfa-Beta Vassilopoulos logo", "AB Vassilopoulos logo"],
    note: "The «ΑΒ» monogram tile is the mark.",
  },
  {
    id: "sklavenitis",
    brand: "Σκλαβενίτης",
    sector: "Σούπερ μάρκετ",
    accept: ["Σκλαβενίτης", "Σκλαβενιτης", "Sklavenitis"],
    search: ["Sklavenitis logo"],
  },
  {
    id: "masoutis",
    brand: "Μασούτης",
    sector: "Σούπερ μάρκετ",
    accept: ["Μασούτης", "Μασουτης", "Masoutis"],
    search: ["Masoutis logo"],
  },
  {
    id: "my-market",
    brand: "My Market",
    sector: "Σούπερ μάρκετ",
    accept: ["My Market", "Μάι Μάρκετ", "Μαι Μαρκετ", "MyMarket", "Metro"],
    search: ["My Market logo", "Metro AEBE logo"],
  },
  {
    id: "galaxias",
    brand: "Γαλαξίας",
    sector: "Σούπερ μάρκετ",
    accept: ["Γαλαξίας", "Γαλαξιας", "Galaxias"],
    search: ["Galaxias supermarket logo"],
  },
  {
    id: "kritikos",
    brand: "Κρητικός",
    sector: "Σούπερ μάρκετ",
    accept: ["Κρητικός", "Κρητικος", "Kritikos"],
    search: ["Kritikos supermarket logo"],
  },
  {
    id: "bazaar",
    brand: "Bazaar",
    sector: "Σούπερ μάρκετ",
    accept: ["Bazaar", "Μπαζάαρ", "Μπαζααρ"],
    search: ["Bazaar supermarket logo"],
  },
  {
    id: "lidl-hellas",
    brand: "Lidl",
    sector: "Σούπερ μάρκετ",
    accept: ["Lidl", "Λιντλ", "Λίντλ"],
    search: ["Lidl logo"],
    note: "FOREIGN — German. Likely reject per the Greek-scope rule; kept only for the eye check.",
  },

  // ─── Μεταφορές ───────────────────────────────────────────────────────────
  {
    id: "olympic-airways",
    brand: "Olympic Airways",
    sector: "Μεταφορές",
    accept: ["Olympic Airways", "Ολυμπιακή", "Ολυμπιακη", "Ολυμπιακή Αεροπορία", "Olympic", "Olympic Air"],
    search: ["Olympic Airways logo", "Olympic Air logo"],
    note: "DEFUNCT/nostalgia — the six meander rings are one of the strongest Greek marks.",
  },
  {
    id: "blue-star-ferries",
    brand: "Blue Star Ferries",
    sector: "Μεταφορές",
    accept: ["Blue Star Ferries", "Blue Star", "Μπλε Σταρ", "Μπλου Σταρ"],
    search: ["Blue Star Ferries logo"],
    note: "The star is the separable mark.",
  },
  {
    id: "superfast-ferries",
    brand: "Superfast Ferries",
    sector: "Μεταφορές",
    accept: ["Superfast Ferries", "Superfast", "Σούπερφαστ", "Σουπερφαστ"],
    search: ["Superfast Ferries logo"],
  },
  {
    id: "anek-lines",
    brand: "ANEK Lines",
    sector: "Μεταφορές",
    accept: ["ANEK", "ANEK Lines", "ΑΝΕΚ", "Άνεκ", "Ανεκ"],
    search: ["ANEK Lines logo"],
  },
  {
    id: "minoan-lines",
    brand: "Minoan Lines",
    sector: "Μεταφορές",
    accept: ["Minoan Lines", "Minoan", "Μινωικές Γραμμές", "Μινωικες Γραμμες", "Μινωικές"],
    search: ["Minoan Lines logo"],
  },
  {
    id: "attica-group",
    brand: "Attica Group",
    sector: "Μεταφορές",
    accept: ["Attica Group", "Αττικα Γκρουπ", "Αττική Γκρουπ"],
    search: ["Attica Group logo"],
  },
  {
    id: "seajets",
    brand: "SeaJets",
    sector: "Μεταφορές",
    accept: ["SeaJets", "Sea Jets", "Σίτζετς", "Σιτζετς"],
    search: ["SeaJets logo"],
  },
  {
    id: "hellenic-seaways",
    brand: "Hellenic Seaways",
    sector: "Μεταφορές",
    accept: ["Hellenic Seaways", "Χέλενικ Σίγουεης", "Ελληνικές Γραμμές"],
    search: ["Hellenic Seaways logo"],
  },
  {
    id: "hellenic-train",
    brand: "Hellenic Train",
    sector: "Μεταφορές",
    accept: ["Hellenic Train", "ΟΣΕ", "OSE", "ΤΡΑΙΝΟΣΕ", "TrainOSE", "Τραινοσέ"],
    search: ["Hellenic Train logo", "TrainOSE logo", "OSE logo"],
  },
  {
    id: "stasy",
    brand: "ΣΤΑΣΥ",
    sector: "Μεταφορές",
    accept: ["ΣΤΑΣΥ", "STASY", "Στασυ", "Σταθερές Συγκοινωνίες"],
    search: ["STASY logo", "Athens Metro logo"],
  },
  {
    id: "oasa",
    brand: "ΟΑΣΑ",
    sector: "Μεταφορές",
    accept: ["ΟΑΣΑ", "OASA", "Οασα"],
    search: ["OASA logo"],
  },
  {
    id: "levante-ferries",
    brand: "Levante Ferries",
    sector: "Μεταφορές",
    accept: ["Levante Ferries", "Levante", "Λεβάντε", "Λεβαντε"],
    search: ["Levante Ferries logo"],
  },
  {
    id: "golden-star-ferries",
    brand: "Golden Star Ferries",
    sector: "Μεταφορές",
    accept: ["Golden Star Ferries", "Golden Star", "Γκόλντεν Σταρ"],
    search: ["Golden Star Ferries logo"],
  },
  {
    id: "fast-ferries",
    brand: "Fast Ferries",
    sector: "Μεταφορές",
    accept: ["Fast Ferries", "Φαστ Φέρις", "Φαστ Φερις"],
    search: ["Fast Ferries logo"],
  },

  // ─── Καύσιμα ─────────────────────────────────────────────────────────────
  {
    id: "eko",
    brand: "ΕΚΟ",
    sector: "Καύσιμα",
    accept: ["ΕΚΟ", "EKO", "Εκο"],
    search: ["EKO fuel logo", "EKO Hellenic Petroleum logo"],
    note: "Flame mark.",
  },
  {
    id: "coral",
    brand: "Coral",
    sector: "Καύσιμα",
    accept: ["Coral", "Κόραλ", "Κοραλ"],
    search: ["Coral Gas logo", "Coral AE logo"],
  },
  {
    id: "avin",
    brand: "Avin",
    sector: "Καύσιμα",
    accept: ["Avin", "Άβιν", "Αβιν"],
    search: ["Avin Oil logo"],
  },
  {
    id: "jetoil",
    brand: "Jetoil",
    sector: "Καύσιμα",
    accept: ["Jetoil", "Τζέτοϊλ", "Τζετοιλ"],
    search: ["Jetoil logo"],
    note: "DEFUNCT — nostalgia mark.",
  },
  {
    id: "aegean-oil",
    brand: "Aegean Oil",
    sector: "Καύσιμα",
    accept: ["Aegean Oil", "Έιτζιαν Όιλ", "Αιγαίον Όιλ"],
    search: ["Aegean Oil logo"],
  },
  {
    id: "revoil",
    brand: "Revoil",
    sector: "Καύσιμα",
    accept: ["Revoil", "Ρεβόιλ", "Ρεβοιλ"],
    search: ["Revoil logo"],
  },
  {
    id: "silkoil",
    brand: "Silk Oil",
    sector: "Καύσιμα",
    accept: ["Silk Oil", "Silkoil", "Σιλκ Όιλ", "Σιλκοιλ"],
    search: ["Silk Oil logo", "Silkoil logo"],
  },
  {
    id: "eteka",
    brand: "ΕΤΕΚΑ",
    sector: "Καύσιμα",
    accept: ["ΕΤΕΚΑ", "ETEKA", "Ετεκα"],
    search: ["ETEKA logo"],
  },
  {
    id: "elin",
    brand: "ELIN",
    sector: "Καύσιμα",
    accept: ["ELIN", "ΕΛΙΝ", "Έλιν", "Ελιν", "Elinoil", "ΕΛΙΝΟΙΛ"],
    search: ["ELIN logo", "Elinoil logo"],
    note: "Same group as ΕΛΙΝΟΙΛ — accept both names.",
  },

  // ─── Τρόφιμα ───────────────────────────────────────────────────────
  {
    id: "delta",
    brand: "ΔΕΛΤΑ",
    sector: "Τρόφιμα",
    accept: ["ΔΕΛΤΑ", "Δέλτα", "Δελτα", "Delta"],
    search: ["Delta Foods logo", "Delta dairy logo"],
  },
  {
    id: "nounou",
    brand: "ΝΟΥΝΟΥ",
    sector: "Τρόφιμα",
    accept: ["ΝΟΥΝΟΥ", "Νουνού", "Νουνου", "Nounou", "NOYNOY"],
    search: ["Nounou milk logo", "NOYNOY logo"],
    note: "Mascot mark — strong candidate if the bear/child figure separates.",
  },
  {
    id: "mevgal",
    brand: "Μέβγαλ",
    sector: "Τρόφιμα",
    accept: ["Μέβγαλ", "Μεβγαλ", "Mevgal"],
    search: ["Mevgal logo"],
  },
  {
    id: "olympos",
    brand: "Όλυμπος",
    sector: "Τρόφιμα",
    accept: ["Όλυμπος", "Ολυμπος", "Olympos"],
    search: ["Olympos dairy logo"],
  },
  {
    id: "fage",
    brand: "ΦΑΓΕ",
    sector: "Τρόφιμα",
    accept: ["ΦΑΓΕ", "Φάγε", "Φαγε", "FAGE"],
    search: ["FAGE logo"],
  },
  {
    id: "kri-kri",
    brand: "Κρι Κρι",
    sector: "Τρόφιμα",
    accept: ["Κρι Κρι", "Κρι-Κρι", "Kri Kri", "Kri-Kri"],
    search: ["Kri Kri logo"],
  },
  {
    id: "evga",
    brand: "ΕΒΓΑ",
    sector: "Τρόφιμα",
    accept: ["ΕΒΓΑ", "EVGA", "Εβγα"],
    search: ["EVGA Greece ice cream logo", "ΕΒΓΑ παγωτό logo", "EVGA Greek dairy logo"],
  },
  {
    id: "giannotiko",
    brand: "Γιαννιώτικο",
    sector: "Τρόφιμα",
    accept: ["Γιαννιώτικο", "Γιαννιωτικο", "Giannotiko", "Γιαννιώτικο Γάλα"],
    search: ["Giannotiko galaktokomika logo"],
  },
  {
    id: "agno",
    brand: "ΑΓΝΟ",
    sector: "Τρόφιμα",
    accept: ["ΑΓΝΟ", "AGNO", "Αγνο"],
    search: ["AGNO dairy logo"],
  },

  // ─── Υγρά ────────────────────────────────────────────────────────────────
  {
    id: "vikos",
    brand: "Βίκος",
    sector: "Υγρά",
    accept: ["Βίκος", "Βικος", "Vikos"],
    search: ["Vikos water logo", "Vikos SA logo"],
  },
  {
    id: "loux",
    brand: "Λουξ",
    sector: "Υγρά",
    accept: ["Λουξ", "Loux"],
    search: ["Loux logo"],
  },
  {
    id: "epsa",
    brand: "ΕΨΑ",
    sector: "Υγρά",
    accept: ["ΕΨΑ", "Έψα", "Εψα", "EPSA"],
    search: null,
    note: "MANUAL — no usable asset found by Commons, official site, Wikipedia or Wayback.",
  },
  {
    id: "ivi",
    brand: "Ήβη",
    sector: "Υγρά",
    accept: ["Ήβη", "Ηβη", "IVI", "Ivi"],
    search: ["Ivi soft drink logo"],
  },
  {
    id: "3e",
    brand: "3Ε",
    sector: "Υγρά",
    accept: ["3Ε", "3E", "Coca-Cola 3E", "Coca-Cola HBC"],
    search: ["Coca-Cola HBC logo"],
    note: "Likely REJECT — reads as Coca-Cola (foreign master brand).",
  },
  {
    id: "sprite",
    brand: "Sprite",
    sector: "Υγρά",
    accept: ["Sprite", "Σπράιτ", "Σπραιτ"],
    search: ["Sprite logo"],
  },
  {
    id: "fanta",
    brand: "Fanta",
    sector: "Υγρά",
    accept: ["Fanta", "Φάντα", "Φαντα"],
    search: ["Fanta logo"],
  },
  {
    id: "nestea",
    brand: "Nestea",
    sector: "Υγρά",
    accept: ["Nestea", "Νεστέα", "Νεστεα"],
    search: ["Nestea logo"],
  },
  {
    id: "lipton-ice-tea",
    brand: "Lipton Ice Tea",
    sector: "Υγρά",
    accept: ["Lipton Ice Tea", "Ice Tea", "Λίπτον", "Λιπτον", "Lipton"],
    search: ["Lipton Ice Tea logo", "Lipton logo"],
  },
  {
    id: "pepsi",
    brand: "Pepsi",
    sector: "Υγρά",
    accept: ["Pepsi", "Πέπσι", "Πεπσι"],
    search: ["Pepsi logo"],
    note: "The globe roundel is a textbook icon-only mark.",
  },
  {
    id: "three-cents",
    brand: "Three Cents",
    sector: "Υγρά",
    accept: ["Three Cents", "3 Cents", "Θρι Σεντς", "3cents"],
    search: ["Three Cents logo"],
  },
  {
    id: "amita",
    brand: "Amita",
    sector: "Υγρά",
    accept: ["Amita", "Αμίτα", "Αμιτα"],
    search: ["Amita logo", "Amita juice logo"],
  },
  {
    id: "athinaiki-zythopoiia",
    brand: "Αθηναϊκή Ζυθοποιία",
    sector: "Υγρά",
    accept: ["Αθηναϊκή Ζυθοποιία", "Αθηναικη Ζυθοποιια", "Athenian Brewery", "Αθηναϊκή"],
    search: ["Athenian Brewery logo", "Αθηναϊκή Ζυθοποιία logo"],
  },
  {
    id: "mythos",
    brand: "Mythos",
    sector: "Υγρά",
    accept: ["Mythos", "Μύθος", "Μυθος", "Μπίρα Μύθος"],
    search: ["Mythos beer logo"],
  },
  {
    id: "alfa-beer",
    brand: "ΑΛΦΑ",
    sector: "Υγρά",
    accept: ["ΑΛΦΑ", "Άλφα", "Αλφα", "Alfa", "Alfa beer", "Μπίρα Άλφα"],
    search: ["Alfa beer logo", "Alfa Hellenic beer logo"],
    note: "Disambiguate from Alpha Bank / Alpha TV in the accept-list on approval.",
  },
  {
    id: "fix-hellas",
    brand: "FIX Hellas",
    sector: "Υγρά",
    accept: ["FIX", "Fix", "FIX Hellas", "Φιξ", "Φιξ Ελλας", "Μπίρα Φιξ"],
    search: ["Fix Hellas logo", "Fix beer logo"],
  },
  {
    id: "vergina-beer",
    brand: "Βεργίνα",
    sector: "Υγρά",
    accept: ["Βεργίνα", "Βεργινα", "Vergina", "Vergina beer", "Μπίρα Βεργίνα"],
    search: ["Vergina beer logo", "Macedonian Thrace Brewery logo"],
    note: "The Vergina sun is a textbook icon-only mark.",
  },
  {
    id: "nissos",
    brand: "Νήσος",
    sector: "Υγρά",
    accept: ["Νήσος", "Νησος", "Nissos", "Μπίρα Νήσος"],
    search: null,
    note: "MANUAL — every pass returns the ΕΛΛΑ-ΔΙΚΑ ΜΑΣ certification badge instead of the mark.",
  },
  {
    id: "septem",
    brand: "Septem",
    sector: "Υγρά",
    accept: ["Septem", "Σέπτεμ", "Σεπτεμ"],
    search: ["Septem microbrewery logo"],
  },
  {
    id: "amstel",
    brand: "Amstel",
    sector: "Υγρά",
    accept: ["Amstel", "Άμστελ", "Αμστελ"],
    search: ["Amstel logo"],
  },
  {
    id: "heineken",
    brand: "Heineken",
    sector: "Υγρά",
    accept: ["Heineken", "Χάινεκεν", "Χαινεκεν"],
    search: ["Heineken logo"],
  },
  {
    id: "boutari",
    brand: "Μπουτάρη",
    sector: "Υγρά",
    accept: ["Μπουτάρη", "Μπουταρη", "Boutari", "Μπουτάρης"],
    search: null,
    note: "MANUAL — the site shows award badges only, no brand mark.",
  },
  {
    id: "malamatina",
    brand: "Μαλαματίνα",
    sector: "Υγρά",
    accept: ["Μαλαματίνα", "Μαλαματινα", "Malamatina", "Ρετσίνα Μαλαματίνα"],
    search: null,
    note: "MANUAL — favicon only.",
  },
  {
    id: "lazaridi",
    brand: "Κτήμα Λαζαρίδη",
    sector: "Υγρά",
    accept: ["Κτήμα Λαζαρίδη", "Κτημα Λαζαριδη", "Λαζαρίδη", "Lazaridi", "Domaine Lazaridi"],
    search: ["Domaine Costa Lazaridi logo", "Ktima Lazaridi logo"],
  },
  {
    id: "plomari",
    brand: "Ούζο Πλωμαρίου",
    sector: "Υγρά",
    accept: ["Πλωμαρίου", "Πλωμαριου", "Ούζο Πλωμαρίου", "Plomari", "Plomariou", "Βαρβαγιάννη"],
    search: ["Ouzo Plomariou logo", "Isidoros Arvanitis ouzo logo"],
  },
  {
    id: "barbayanni",
    brand: "Βαρβαγιάννη",
    sector: "Υγρά",
    accept: ["Βαρβαγιάννη", "Βαρβαγιαννη", "Barbayanni", "Ούζο Βαρβαγιάννη"],
    search: ["Barbayanni ouzo logo"],
  },
  {
    id: "metaxa",
    brand: "Metaxa",
    sector: "Υγρά",
    accept: ["Metaxa", "Μεταξά", "Μεταξα", "Μεταξάς"],
    search: ["Metaxa logo"],
    note: "The star/asterism mark is separable.",
  },
  {
    id: "tsipouro-tirnavou",
    brand: "Τσίπουρο Τυρνάβου",
    sector: "Υγρά",
    accept: ["Τσίπουρο Τυρνάβου", "Τσιπουρο Τυρναβου", "Τυρνάβου", "Tirnavou"],
    search: ["Tsipouro Tirnavou logo"],
  },
  {
    id: "zagori",
    brand: "Ζαγόρι",
    sector: "Υγρά",
    accept: ["Ζαγόρι", "Ζαγορι", "Zagori", "Ζαγόρι Νερό"],
    search: ["Zagori water logo"],
  },
  {
    id: "avra",
    brand: "Αύρα",
    sector: "Υγρά",
    accept: ["Αύρα", "Αυρα", "Avra", "Νερό Αύρα"],
    search: ["Avra water logo"],
  },
  {
    id: "theoni",
    brand: "Θεόνη",
    sector: "Υγρά",
    accept: ["Θεόνη", "Θεονη", "Theoni"],
    search: ["Theoni water logo"],
  },
  {
    id: "souroti",
    brand: "Σουρωτή",
    sector: "Υγρά",
    accept: ["Σουρωτή", "Σουρωτη", "Souroti"],
    search: ["Souroti water logo"],
  },
  {
    id: "ioli",
    brand: "Ιόλη",
    sector: "Υγρά",
    accept: ["Ιόλη", "Ιολη", "Ioli"],
    search: ["Ioli water logo"],
  },
  {
    id: "korpi",
    brand: "Κορπή",
    sector: "Υγρά",
    accept: ["Κορπή", "Κορπη", "Korpi"],
    search: ["Korpi water logo"],
  },
  {
    id: "evian",
    brand: "Evian",
    sector: "Υγρά",
    accept: ["Evian", "Εβιάν", "Εβιαν"],
    search: ["Evian logo"],
  },
  {
    id: "doubles",
    brand: "Δουμπιά",
    sector: "Υγρά",
    accept: ["Δουμπιά", "Δουμπια", "Doumpia"],
    search: ["Doumpia water logo"],
  },

  // ─── Τρόφιμα ─────────────────────────────────────────────────────────────
  {
    id: "chipita",
    brand: "Chipita",
    sector: "Τρόφιμα",
    accept: ["Chipita", "Τσιπίτα", "Τσιπιτα", "7Days", "Molto"],
    search: ["Chipita logo", "7Days Chipita logo"],
  },
  {
    id: "papadopoulou",
    brand: "Παπαδοπούλου",
    sector: "Τρόφιμα",
    accept: ["Παπαδοπούλου", "Παπαδοπουλου", "Παπαδόπουλος", "Papadopoulou", "Ε.Ι. Παπαδοπούλου"],
    search: ["Papadopoulou biscuits logo", "E.I. Papadopoulos logo"],
  },
  {
    id: "ion",
    brand: "ΙΟΝ",
    sector: "Τρόφιμα",
    accept: ["ΙΟΝ", "Ίον", "Ιον", "ION"],
    search: ["ION chocolate logo"],
  },
  {
    id: "misko",
    brand: "Misko",
    sector: "Τρόφιμα",
    accept: ["Misko", "Μίσκο", "Μισκο"],
    search: ["Misko pasta logo"],
  },
  {
    id: "melissa",
    brand: "Μέλισσα",
    sector: "Τρόφιμα",
    accept: ["Μέλισσα", "Μελισσα", "Melissa", "Μέλισσα Κίκιζας"],
    search: ["Melissa Kikizas logo"],
    note: "A bee mark would be ideal for the icon-only filter.",
  },
  {
    id: "barba-stathis",
    brand: "Μπάρμπα Στάθης",
    sector: "Τρόφιμα",
    accept: ["Μπάρμπα Στάθης", "Μπαρμπα Σταθης", "Barba Stathis", "Μπαρμπαστάθης"],
    search: ["Barba Stathis logo"],
    note: "Mascot (the old man) — strong icon candidate.",
  },
  {
    id: "allatini",
    brand: "Αλλατίνη",
    sector: "Τρόφιμα",
    accept: ["Αλλατίνη", "Αλλατινη", "Allatini"],
    search: ["Allatini logo"],
  },
  {
    id: "kyknos",
    brand: "ΚΥΚΝΟΣ",
    sector: "Τρόφιμα",
    accept: ["ΚΥΚΝΟΣ", "Κύκνος", "Κυκνος", "Kyknos"],
    search: null,
    note: "MANUAL — the swan roundel exists but only inside a warehouse photo.",
  },
  {
    id: "loumidis",
    brand: "Λουμίδης",
    sector: "Τρόφιμα",
    accept: ["Λουμίδης", "Λουμιδης", "Loumidis", "Λουμίδη Παπαγάλος", "Παπαγάλος"],
    search: ["Loumidis Papagalos logo"],
    note: "The parrot (Παπαγάλος) is a superb icon-only mark.",
  },
  {
    id: "nescafe",
    brand: "Nescafé",
    sector: "Τρόφιμα",
    accept: ["Nescafé", "Nescafe", "Νεσκαφέ", "Νεσκαφε"],
    search: ["Nescafe logo"],
  },
  {
    id: "pavlidis",
    brand: "Παυλίδης",
    sector: "Τρόφιμα",
    accept: ["Παυλίδης", "Παυλιδης", "Pavlidis", "Σοκολάτα Παυλίδη"],
    search: null,
    note: "MANUAL — pavlidis.gr is a DIFFERENT Παυλίδης (optician); the chocolate brand is a Mondelez sub-brand with no own site.",
  },
  {
    id: "lacta",
    brand: "Lacta",
    sector: "Τρόφιμα",
    accept: ["Lacta", "Λακτά", "Λακτα"],
    search: ["Lacta chocolate logo"],
  },
  {
    id: "terkenlis",
    brand: "Τερκενλής",
    sector: "Τρόφιμα",
    accept: ["Τερκενλής", "Τερκενλης", "Terkenlis", "Τσουρέκι Τερκενλής"],
    search: ["Terkenlis logo"],
  },
  {
    id: "tsakiris",
    brand: "Τσακίρης",
    sector: "Τρόφιμα",
    accept: ["Τσακίρης", "Τσακιρης", "Tsakiris", "Τσακίρης Chips"],
    search: ["Tsakiris chips logo"],
  },
  {
    id: "sevendays",
    brand: "7Days",
    sector: "Τρόφιμα",
    accept: ["7Days", "7 Days", "Σέβεν Ντέις", "Seven Days"],
    search: null,
    note: "MANUAL — 7days.com redirects to Mondelez corporate; no 7Days-specific mark online.",
  },
  {
    id: "lay-s",
    brand: "Lay's",
    sector: "Τρόφιμα",
    accept: ["Lay's", "Lays", "Λέις", "Λειs"],
    search: ["Lay's logo"],
  },
  {
    id: "elite-tsakiris",
    brand: "Ελίτ",
    sector: "Τρόφιμα",
    accept: ["Ελίτ", "Ελιτ", "Elite"],
    search: ["Elite snacks Greece logo"],
  },
  {
    id: "minerva",
    brand: "Μινέρβα",
    sector: "Τρόφιμα",
    accept: ["Μινέρβα", "Μινερβα", "Minerva"],
    search: ["Minerva Greece food logo"],
  },
  {
    id: "altis",
    brand: "Altis",
    sector: "Τρόφιμα",
    accept: ["Altis", "Άλτις", "Αλτις"],
    search: ["Altis olive oil logo"],
  },
  {
    id: "gioutis",
    brand: "Γιώτης",
    sector: "Τρόφιμα",
    accept: ["Γιώτης", "Γιωτης", "Giotis", "Yiotis"],
    search: null,
    note: "MANUAL — favicon only.",
  },
  {
    id: "knorr",
    brand: "Knorr",
    sector: "Τρόφιμα",
    accept: ["Knorr", "Κνορ", "Κνορρ"],
    search: ["Knorr logo"],
  },

  // ─── Εστίαση ─────────────────────────────────────────────────────────────
  {
    id: "goodys",
    brand: "Goody's",
    sector: "Εστίαση",
    accept: ["Goody's", "Goodys", "Γκούντις", "Γκουντις", "Goody s"],
    search: ["Goody's logo"],
    note: "Foreign-owned but perceived Greek — allowed by the rules.",
  },
  {
    id: "coffee-island",
    brand: "Coffee Island",
    sector: "Εστίαση",
    accept: ["Coffee Island", "Κόφι Άιλαντ", "Κοφι Αιλαντ"],
    search: ["Coffee Island logo"],
  },
  {
    id: "mikel",
    brand: "Mikel",
    sector: "Εστίαση",
    accept: ["Mikel", "Μάικελ", "Μαικελ", "Mikel Coffee"],
    search: ["Mikel Coffee Company logo"],
  },
  {
    id: "flocafe",
    brand: "Flocafe",
    sector: "Εστίαση",
    accept: ["Flocafe", "Φλοκαφέ", "Φλοκαφε"],
    search: ["Flocafe logo"],
  },
  {
    id: "pizza-fan",
    brand: "Pizza Fan",
    sector: "Εστίαση",
    accept: ["Pizza Fan", "Πίτσα Φαν", "Πιτσα Φαν", "PizzaFan"],
    search: ["Pizza Fan logo"],
  },
  {
    id: "simply-burgers",
    brand: "Simply Burgers",
    sector: "Εστίαση",
    accept: ["Simply Burgers", "Σίμπλι Μπέργκερς", "Simply"],
    search: ["Simply Burgers logo"],
  },
  {
    id: "subway",
    brand: "Subway",
    sector: "Εστίαση",
    accept: ["Subway", "Σάμπγουεϊ", "Σαμπγουει"],
    search: ["Subway-logo-green 2016", "Subway restaurants logo"],
  },
  {
    id: "starbucks",
    brand: "Starbucks",
    sector: "Εστίαση",
    accept: ["Starbucks", "Στάρμπακς", "Σταρμπακς"],
    search: ["Starbucks logo"],
    note: "Siren mark — pure icon, no wordmark needed.",
  },
  {
    id: "coffee-lab",
    brand: "Coffee Lab",
    sector: "Εστίαση",
    accept: ["Coffee Lab", "Κόφι Λαμπ", "Κοφι Λαμπ"],
    search: null,
    note: "MANUAL — site serves only a 75×88 bulldog mascot; too small for the canvas.",
  },
  {
    id: "second-cup",
    brand: "Second Cup",
    sector: "Εστίαση",
    accept: ["Second Cup", "Σέκοντ Καπ", "Σεκοντ Καπ"],
    search: ["Second Cup logo"],
  },
  {
    id: "taf-coffee",
    brand: "TAF Coffee",
    sector: "Εστίαση",
    accept: ["TAF Coffee", "TAF", "Ταφ"],
    search: ["TAF Coffee logo"],
  },
  {
    id: "roast-bakery",
    brand: "Roast",
    sector: "Εστίαση",
    accept: ["Roast", "Ρόαστ", "Ροαστ"],
    search: ["Roast coffee Greece logo"],
  },

  // ─── Εταιρείες ─────────────────────────────────────────────────────────────
  {
    id: "public",
    brand: "Public",
    sector: "Εταιρείες",
    accept: ["Public", "Πάμπλικ", "Παμπλικ"],
    search: null,
    note: "PoC ○ manual — no clean public SVG; source from public.gr by hand.",
  },
  {
    id: "kotsovolos",
    brand: "Κωτσόβολος",
    sector: "Εταιρείες",
    accept: ["Κωτσόβολος", "Κωτσοβολος", "Kotsovolos"],
    search: ["Kotsovolos logo"],
  },
  {
    id: "plaisio",
    brand: "Πλαίσιο",
    sector: "Εταιρείες",
    accept: ["Πλαίσιο", "Πλαισιο", "Plaisio"],
    search: ["Plaisio logo"],
  },
  {
    id: "jumbo",
    brand: "Jumbo",
    sector: "Εταιρείες",
    accept: ["Jumbo", "Τζάμπο", "Τζαμπο"],
    search: ["Jumbo SA logo"],
    note: "Likely wordmark-only — verify.",
  },
  {
    id: "hondos-center",
    brand: "Hondos Center",
    sector: "Εταιρείες",
    accept: ["Hondos Center", "Χονδρός", "Χόντος", "Χοντος Σεντερ"],
    search: ["Hondos Center logo"],
  },
  {
    id: "praktiker",
    brand: "Praktiker",
    sector: "Εταιρείες",
    accept: ["Praktiker", "Πρακτίκερ", "Πρακτικερ"],
    search: ["Praktiker logo"],
  },
  {
    id: "notos-galleries",
    brand: "Notos Galleries",
    sector: "Εταιρείες",
    accept: ["Notos Galleries", "Νότος", "Νοτος", "Notos"],
    search: ["Notos Galleries logo"],
  },
  {
    id: "intersport",
    brand: "Intersport",
    sector: "Εταιρείες",
    accept: ["Intersport", "Ίντερσπορτ", "Ιντερσπορτ"],
    search: ["Intersport logo"],
  },
  {
    id: "moustakas",
    brand: "Παιχνίδια Μουστάκας",
    sector: "Εταιρείες",
    accept: ["Μουστάκας", "Μουστακας", "Moustakas", "Παιχνίδια Μουστάκας"],
    search: ["Moustakas toys logo"],
  },
  {
    id: "attica-stores",
    brand: "attica",
    sector: "Εταιρείες",
    accept: ["attica", "Αττικα", "Αττική", "attica department stores"],
    search: ["attica department stores logo"],
  },
  {
    id: "factory-outlet",
    brand: "Factory Outlet",
    sector: "Εταιρείες",
    accept: ["Factory Outlet", "Φάκτορι Άουτλετ", "Φακτορι Αουτλετ"],
    search: ["Factory Outlet Greece logo"],
  },
  {
    id: "leroy-merlin",
    brand: "Leroy Merlin",
    sector: "Εταιρείες",
    accept: ["Leroy Merlin", "Λερουά Μερλέν", "Λερουα Μερλεν"],
    search: ["Leroy Merlin logo"],
  },
  {
    id: "ikea",
    brand: "IKEA",
    sector: "Εταιρείες",
    accept: ["IKEA", "Ικέα", "Ικεα"],
    search: ["IKEA logo"],
  },
  {
    id: "zara",
    brand: "Zara",
    sector: "Εταιρείες",
    accept: ["Zara", "Ζάρα", "Ζαρα"],
    search: ["Zara logo"],
  },
  {
    id: "sklavenitis-cash",
    brand: "The Mart",
    sector: "Εταιρείες",
    accept: ["The Mart", "Δε Μαρτ", "TheMart"],
    search: ["The Mart Sklavenitis logo"],
  },

  // ─── Εταιρείες ─────────────────────────────────────────────────
  {
    id: "skroutz",
    brand: "Skroutz",
    sector: "Εταιρείες",
    accept: ["Skroutz", "Σκρουτζ", "Σκρούτζ"],
    search: ["Skroutz logo"],
    note: "The shopping-bag mark is a clean icon.",
  },
  {
    id: "car-gr",
    brand: "Car.gr",
    sector: "Εταιρείες",
    accept: ["Car.gr", "Car gr", "Κάρ", "Cargr"],
    search: ["Car.gr logo"],
  },
  {
    id: "spitogatos",
    brand: "Spitogatos",
    sector: "Εταιρείες",
    accept: ["Spitogatos", "Σπιτόγατος", "Σπιτογατος"],
    search: ["Spitogatos logo"],
    note: "A cat mark would be a perfect icon — verify.",
  },
  {
    id: "xe-gr",
    brand: "XE.gr",
    sector: "Εταιρείες",
    accept: ["XE.gr", "XE", "Χρυσή Ευκαιρία", "Χρυση Ευκαιρια", "Xe gr"],
    search: ["XE.gr logo", "Chrysi Efkairia logo"],
  },

  // ─── Delivery ────────────────────────────────────────────────────────────
  {
    id: "efood",
    brand: "efood",
    sector: "Delivery",
    accept: ["efood", "e-food", "Ίφουντ", "Ιφουντ", "e food"],
    search: ["efood logo", "e-food logo"],
  },
  {
    id: "box",
    brand: "BOX",
    sector: "Delivery",
    accept: ["BOX", "Box", "Μποξ", "Μπόξ"],
    search: ["BOX delivery Greece logo"],
  },
  {
    id: "elta",
    brand: "ΕΛΤΑ",
    sector: "Delivery",
    accept: ["ΕΛΤΑ", "ELTA", "Ελτα", "Ελληνικά Ταχυδρομεία"],
    search: ["Hellenic Post logo", "ELTA logo"],
  },
  {
    id: "acs",
    brand: "ACS",
    sector: "Delivery",
    accept: ["ACS", "Έι Σι Ες", "Ειcιες"],
    search: ["ACS Courier logo"],
  },
  {
    id: "geniki-taxydromiki",
    brand: "Γενική Ταχυδρομική",
    sector: "Delivery",
    accept: ["Γενική Ταχυδρομική", "Γενικη Ταχυδρομικη", "Geniki Taxydromiki"],
    search: ["Geniki Taxydromiki logo"],
  },
  {
    id: "dhl",
    brand: "DHL",
    sector: "Delivery",
    accept: ["DHL", "Ντι Έιτς Ελ", "Ντιέιτσελ"],
    search: ["DHL logo"],
  },
  {
    id: "elta-courier",
    brand: "ΕΛΤΑ Courier",
    sector: "Delivery",
    accept: ["ΕΛΤΑ Courier", "ELTA Courier", "Ελτα Κούριερ", "ΕΛΤΑ Κούριερ"],
    search: ["ELTA Courier logo", "Hellenic Post courier logo"],
  },
  {
    id: "icc-courier",
    brand: "ICC Courier",
    sector: "Delivery",
    accept: ["ICC Courier", "ICC", "Άι Σι Σι"],
    search: ["ICC Courier logo"],
  },
  {
    id: "wolt",
    brand: "Wolt",
    sector: "Delivery",
    accept: ["Wolt", "Βολτ", "Γουόλτ", "Γουολτ"],
    search: ["Wolt logo"],
  },

  // ─── Τυχερά παιχνίδια ────────────────────────────────────────────────────
  {
    id: "opap",
    brand: "ΟΠΑΠ",
    sector: "Τυχερά παιχνίδια",
    accept: ["ΟΠΑΠ", "OPAP", "Οπαπ"],
    search: ["OPAP logo"],
  },
  {
    id: "stoiximan",
    brand: "Stoiximan",
    sector: "Τυχερά παιχνίδια",
    accept: ["Stoiximan", "Στοίχημαν", "Στοιχηματάν", "Στοιχειμαν"],
    search: ["Stoiximan logo"],
  },
  {
    id: "novibet",
    brand: "Novibet",
    sector: "Τυχερά παιχνίδια",
    accept: ["Novibet", "Νόβιμπετ", "Νοβιμπετ"],
    search: ["Novibet logo"],
  },
  {
    id: "bet365",
    brand: "bet365",
    sector: "Τυχερά παιχνίδια",
    accept: ["bet365", "Bet365", "Μπετ 365", "Μπετ365"],
    search: ["bet365 logo"],
  },
  {
    id: "betsson",
    brand: "Betsson",
    sector: "Τυχερά παιχνίδια",
    accept: ["Betsson", "Μπέτσον", "Μπετσον"],
    search: ["Betsson logo"],
  },
  {
    id: "pamestoixima",
    brand: "Πάμε Στοίχημα",
    sector: "Τυχερά παιχνίδια",
    accept: ["Πάμε Στοίχημα", "Παμε Στοιχημα", "Pame Stoixima", "Πάμε Στοίχημα ΟΠΑΠ"],
    search: ["Pame Stoixima logo", "OPAP Pame Stoixima logo"],
    note: "ΟΠΑΠ sub-brand — allowed now that sub-brands are in scope.",
  },
  {
    id: "netbet",
    brand: "NetBet",
    sector: "Τυχερά παιχνίδια",
    accept: ["NetBet", "Net Bet", "Νετμπετ", "Νετμπέτ"],
    search: ["NetBet logo"],
  },
  {
    id: "fonbet",
    brand: "Fonbet",
    sector: "Τυχερά παιχνίδια",
    accept: ["Fonbet", "Φονμπέτ", "Φονμπετ"],
    search: ["Fonbet logo"],
  },
  {
    id: "interwetten",
    brand: "Interwetten",
    sector: "Τυχερά παιχνίδια",
    accept: ["Interwetten", "Ιντερβέτεν", "Ιντερβετεν"],
    search: ["Interwetten logo"],
  },
  {
    id: "tzoker",
    brand: "ΤΖΟΚΕΡ",
    sector: "Τυχερά παιχνίδια",
    accept: ["ΤΖΟΚΕΡ", "Τζόκερ", "Τζοκερ", "Joker", "Tzoker"],
    search: ["Tzoker OPAP logo", "Joker OPAP logo"],
    note: "ΟΠΑΠ lottery sub-brand — the joker face is a strong icon.",
  },
  {
    id: "kino",
    brand: "ΚΙΝΟ",
    sector: "Τυχερά παιχνίδια",
    accept: ["ΚΙΝΟ", "Κίνο", "Κινο", "Kino"],
    search: ["Kino OPAP logo"],
  },

  // ─── Καλλυντικά ──────────────────────────────────────────────────────────
  {
    id: "korres",
    brand: "Korres",
    sector: "Καλλυντικά",
    accept: ["Korres", "Κορρές", "Κορρες"],
    search: ["Korres logo"],
  },
  {
    id: "apivita",
    brand: "Apivita",
    sector: "Καλλυντικά",
    accept: ["Apivita", "Απιβίτα", "Απιβιτα"],
    search: ["Apivita logo"],
    note: "Bee/hive mark — good icon candidate.",
  },
  {
    id: "frezyderm",
    brand: "Frezyderm",
    sector: "Καλλυντικά",
    accept: ["Frezyderm", "Φρεζιντέρμ", "Φρεζιντερμ"],
    search: ["Frezyderm logo"],
  },
  {
    id: "sarantis",
    brand: "Σαράντης",
    sector: "Καλλυντικά",
    accept: ["Σαράντης", "Σαραντης", "Sarantis", "Γρ. Σαράντης"],
    search: ["Sarantis Group logo"],
  },
  {
    id: "papoutsanis",
    brand: "Παπουτσάνης",
    sector: "Καλλυντικά",
    accept: ["Παπουτσάνης", "Παπουτσανης", "Papoutsanis"],
    search: ["Papoutsanis logo"],
  },

  // ─── Εταιρείες ──────────────────────────────────────────────────────────
  {
    id: "titan",
    brand: "ΤΙΤΑΝ",
    sector: "Εταιρείες",
    accept: ["ΤΙΤΑΝ", "Τιτάν", "Τιταν", "Titan", "Titan Cement"],
    search: ["Titan Cement logo"],
  },
  {
    id: "alumil",
    brand: "Alumil",
    sector: "Εταιρείες",
    accept: ["Alumil", "Αλουμίλ", "Αλουμιλ"],
    search: ["Alumil logo"],
  },
  {
    id: "iraklis",
    brand: "Ηρακλής",
    sector: "Εταιρείες",
    accept: ["Ηρακλής", "Ηρακλης", "Iraklis", "ΑΓΕΤ Ηρακλής", "Heracles"],
    search: null,
    note: "MANUAL — lafarge.gr and iraklis.gr both serve the LAFARGE parent logo.",
  },
  {
    id: "pitsos",
    brand: "Πίτσος",
    sector: "Εταιρείες",
    accept: ["Πίτσος", "Πιτσος", "Pitsos"],
    search: ["Pitsos logo"],
  },

  // ─── Εταιρείες ─────────────────────────────────────────────────────────────
  {
    id: "eydap",
    brand: "ΕΥΔΑΠ",
    sector: "Εταιρείες",
    accept: ["ΕΥΔΑΠ", "EYDAP", "Ευδαπ"],
    search: ["EYDAP logo"],
  },
  {
    id: "eyath",
    brand: "ΕΥΑΘ",
    sector: "Εταιρείες",
    accept: ["ΕΥΑΘ", "EYATH", "Ευαθ"],
    search: ["EYATH logo"],
  },

  // ─── Μέσα ενημέρωσης ─────────────────────────────────────────────────────
  {
    id: "ert",
    brand: "ΕΡΤ",
    sector: "Μέσα ενημέρωσης",
    accept: ["ΕΡΤ", "ERT", "Ερτ", "Ελληνική Ραδιοφωνία Τηλεόραση"],
    search: ["ERT logo"],
  },
  {
    id: "mega-channel",
    brand: "MEGA",
    sector: "Μέσα ενημέρωσης",
    accept: ["MEGA", "Μέγκα", "Μεγκα", "Mega Channel"],
    search: ["Mega Channel logo"],
  },
  {
    id: "ant1",
    brand: "ANT1",
    sector: "Μέσα ενημέρωσης",
    accept: ["ANT1", "ΑΝΤ1", "Άντεννα", "Αντεννα", "Antenna"],
    search: ["ANT1 logo", "Antenna TV logo"],
  },
  {
    id: "skai",
    brand: "ΣΚΑΪ",
    sector: "Μέσα ενημέρωσης",
    accept: ["ΣΚΑΪ", "ΣΚΑΙ", "Σκάι", "Σκαι", "SKAI"],
    search: ["Skai TV logo"],
  },
  {
    id: "star-channel",
    brand: "Star",
    sector: "Μέσα ενημέρωσης",
    accept: ["Star", "Σταρ", "Star Channel"],
    search: ["Star Channel logo"],
  },
  {
    id: "alpha-tv",
    brand: "Alpha TV",
    sector: "Μέσα ενημέρωσης",
    accept: ["Alpha TV", "Άλφα TV", "Alpha"],
    search: ["Alpha TV Greece logo"],
  },
  {
    id: "art-tv",
    brand: "ΑΡΤ",
    sector: "Μέσα ενημέρωσης",
    accept: ["ΑΡΤ", "ART", "Αρτ", "ART TV"],
    search: ["ART TV Greece logo"],
  },
  {
    id: "mad-tv",
    brand: "MAD TV",
    sector: "Μέσα ενημέρωσης",
    accept: ["MAD TV", "MAD", "Μαντ", "Μαντ Τι Βι"],
    search: ["MAD TV logo"],
  },
  {
    id: "vouli-tileorasi",
    brand: "Βουλή Τηλεόραση",
    sector: "Μέσα ενημέρωσης",
    accept: ["Βουλή Τηλεόραση", "Βουλη Τηλεοραση", "Βουλή", "Vouli TV"],
    search: ["Vouli Tileorasi logo", "Hellenic Parliament TV logo"],
  },
  {
    id: "novalife",
    brand: "Novalife",
    sector: "Μέσα ενημέρωσης",
    accept: ["Novalife", "Νόβαλαϊφ", "Νοβαλαιφ", "Nova Life"],
    search: ["Novalife logo"],
  },
  {
    id: "rise-tv",
    brand: "RISE TV",
    sector: "Μέσα ενημέρωσης",
    accept: ["RISE TV", "RISE", "Ράιζ", "Ραιζ"],
    search: ["Rise TV Greece logo"],
  },

  // Radio stations (added 2026-07-28 on the operator's request). Station logos
  // are a good fit for the icon-only filter — a frequency dial or a monogram is
  // usually the whole mark — and they deepen an otherwise TV-only sector.
  // Search terms carry a Greece/Athens anchor per the operator's guidance: "Red",
  // "Rhythm", "Melody" and "Sphere" are ordinary English/Greek words that would
  // otherwise match anything on Commons.
  {
    id: "en-lefko",
    brand: "En Lefko 87.7",
    sector: "Μέσα ενημέρωσης",
    accept: ["En Lefko", "Εν Λευκώ", "Εν Λευκω", "En Lefko 87.7", "Ενλευκώ"],
    search: ["En Lefko radio Athens logo", "Εν Λευκώ ραδιόφωνο logo"],
  },
  {
    id: "rythmos",
    brand: "Ρυθμός 94.9",
    sector: "Μέσα ενημέρωσης",
    accept: ["Ρυθμός", "Ρυθμος", "Rythmos", "Ρυθμός 94.9", "Rythmos 94.9"],
    search: null,
    note: "MANUAL — rythmos.gr is Burg-Wachter (German locks), not the station; no other domain found.",
  },
  {
    id: "red-fm",
    brand: "Red 96.3",
    sector: "Μέσα ενημέρωσης",
    accept: ["Red 96.3", "Red FM", "Ρεντ", "Red"],
    search: ["Red 96.3 radio Athens logo", "Red FM Greece radio logo"],
  },
  {
    id: "dromos-fm",
    brand: "Δρόμος 89.8",
    sector: "Μέσα ενημέρωσης",
    accept: ["Δρόμος", "Δρομος", "Dromos", "Δρόμος 89.8", "Dromos FM"],
    search: ["Dromos 89.8 radio Athens logo", "Δρόμος ραδιόφωνο logo"],
  },
  {
    id: "melodia-fm",
    brand: "Μελωδία 99.2",
    sector: "Μέσα ενημέρωσης",
    accept: ["Μελωδία", "Μελωδια", "Melodia", "Μελωδία 99.2", "Melodia FM"],
    search: ["Melodia 99.2 radio Athens logo", "Μελωδία ραδιόφωνο logo"],
  },
  {
    id: "athens-deejay",
    brand: "Athens DeeJay",
    sector: "Μέσα ενημέρωσης",
    accept: ["Athens DeeJay", "Athens Deejay", "AthensDeejay", "Άθενς Ντιτζέι"],
    search: ["Athens DeeJay radio logo"],
  },
  {
    id: "kiss-fm",
    brand: "Kiss 92.9",
    sector: "Μέσα ενημέρωσης",
    accept: ["Kiss FM", "Kiss 92.9", "Κις", "Kiss"],
    search: ["Kiss 92.9 radio Athens logo", "Kiss FM Greece radio logo"],
  },
  {
    id: "diesi",
    brand: "Δίεση 101.3",
    sector: "Μέσα ενημέρωσης",
    accept: ["Δίεση", "Διεση", "Diesi", "Δίεση 101.3"],
    search: ["Diesi 101.3 radio Athens logo", "Δίεση ραδιόφωνο logo"],
  },
  {
    id: "best-radio",
    brand: "Best 92.6",
    sector: "Μέσα ενημέρωσης",
    accept: ["Best 92.6", "Best Radio", "Μπεστ", "Best"],
    search: ["Best 92.6 radio Athens logo", "Best Radio Greece logo"],
  },

  // ─── Μουσική ─────────────────────────────────────────────────────────────
  {
    id: "minos-emi",
    brand: "Minos EMI",
    sector: "Μουσική",
    accept: ["Minos EMI", "Μίνως", "Μινως", "Minos"],
    search: ["Minos EMI logo"],
  },
  {
    id: "panik-records",
    brand: "Panik Records",
    sector: "Μουσική",
    accept: ["Panik Records", "Panik", "Πάνικ", "Πανικ"],
    search: ["Panik Records logo"],
  },
  {
    id: "heaven-music",
    brand: "Heaven Music",
    sector: "Μουσική",
    accept: ["Heaven Music", "Heaven", "Χέβεν", "Χεβεν"],
    search: ["Heaven Music logo"],
  },
  {
    id: "cobalt-music",
    brand: "Cobalt Music",
    sector: "Μουσική",
    accept: ["Cobalt Music", "Cobalt", "Κόμπαλτ", "Κομπαλτ"],
    search: ["Cobalt Music logo"],
  },
  {
    id: "spicy-music",
    brand: "Spicy",
    sector: "Μουσική",
    accept: ["Spicy", "Spicy Music", "Σπάισι", "Σπαισι"],
    search: ["Spicy Music logo"],
  },
  {
    id: "fm-records",
    brand: "FM Records",
    sector: "Μουσική",
    accept: ["FM Records", "FM", "Εφ Εμ Ρέκορντς"],
    search: ["FM Records Greece logo"],
  },

  // ─── Εταιρείες ───────────────────────────────────────────────────────────
  {
    id: "public-cinemas",
    brand: "Village Cinemas",
    sector: "Εταιρείες",
    accept: ["Village Cinemas", "Village", "Βίλατζ", "Βιλατζ"],
    search: ["Village Roadshow Greece logo", "Village Cinemas logo"],
  },

  // ─── Τρόφιμα ───────────────────────────────────────────────────
  {
    id: "ifantis",
    brand: "Υφαντής",
    sector: "Τρόφιμα",
    accept: ["Υφαντής", "Υφαντης", "Ifantis", "Yfantis"],
    search: ["Ifantis logo", "Yfantis logo"],
  },
  {
    id: "nikas",
    brand: "Νίκας",
    sector: "Τρόφιμα",
    accept: ["Νίκας", "Νικας", "Nikas", "Π.Γ. Νίκας"],
    search: ["Nikas logo", "P.G. Nikas logo"],
  },
  {
    id: "creta-farms",
    brand: "Creta Farms",
    sector: "Τρόφιμα",
    accept: ["Creta Farms", "Κρέτα Φαρμς", "Κρετα Φαρμς", "Creta Farm"],
    search: ["Creta Farms logo"],
  },
  {
    id: "venetis",
    brand: "Βενέτης",
    sector: "Εστίαση",
    accept: ["Βενέτης", "Βενετης", "Venetis"],
    search: ["Venetis logo"],
    note: "Bakery chain — may belong to Εστίαση instead; operator's call in review.",
  },
  {
    id: "dodoni",
    brand: "Δωδώνη",
    sector: "Τρόφιμα",
    accept: ["Δωδώνη", "Δωδωνη", "Dodoni", "Φέτα Δωδώνη"],
    search: ["Dodoni logo", "Dodoni feta logo"],
  },
  {
    id: "epirus",
    brand: "Ήπειρος",
    sector: "Τρόφιμα",
    accept: ["Ήπειρος", "Ηπειρος", "Epirus", "Τυροκομικά Ηπείρου"],
    search: ["Epiros cheese logo", "Ipiros tyrokomika logo"],
  },
  {
    id: "olympus-tyri",
    brand: "Τυράς",
    sector: "Τρόφιμα",
    accept: ["Τυράς", "Τυρας", "Tyras", "Όλυμπος Τυράς"],
    search: ["Tyras logo"],
  },
];
